name: Terraform CI/CD

on:
  workflow_dispatch:
    inputs:
      ACTION:
        description: "Choose Action"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy
      INSTANCE_TYPE:
        description: "EC2 Instance Type"
        required: true
        default: "t3.micro"

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: ap-south-1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (with backend)
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="instance_type=${{ github.event.inputs.INSTANCE_TYPE }}"

      - name: Terraform Apply
        if: ${{ github.event.inputs.ACTION == 'apply' }}
        run: terraform apply -auto-approve -var="instance_type=${{ github.event.inputs.INSTANCE_TYPE }}"

      - name: Terraform Destroy
        if: ${{ github.event.inputs.ACTION == 'destroy' }}
        run: terraform destroy -auto-approve -var="instance_type=${{ github.event.inputs.INSTANCE_TYPE }}"

      - name: Show Terraform Outputs
        if: github.event.inputs.ACTION == 'apply'
        run: terraform output

      - name: Cleanup Workspace
        if: always()
        run: |
          echo "Cleaning up workspace..."
          rm -rf *
          echo "Workspace cleaned successfully ✅"
